spring:
    profiles:
        active: development
    application:
        name: config-client
    config:
        import: optional:configserver:http://localhost:8888
management:
    endpoints:
        web:
            exposure:
                include: "*"
